version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/node:10
    working_directory: ~/ecommerce_otop_frontend
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Gatsby Build
          command: npm run build
      - run:
          name: Jest | Unit Test
          command: npm test
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ~/ecommerce_otop_frontend
          # Must be relative path from root
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: circleci/node:10
    # working_directory: ~/ecommerce_otop_frontend
    steps:
      # - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ecommerce_otop_frontend/
      - checkout
      - run:
          name: Firebase Deployjest
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
