version: 2

jobs:
  build_test:
    docker:
      - image: circleci/node:10
    working_directory: ~/ecommerce_otop_frontend
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Gatsby Build
          command: npm run build
      - run:
          name: Jest | Unit Test
          command: npm test

  # test:
  #   docker:
  #     - image: circleci/node:10
  #   working_directory: ~/ecommerce_otop_frontend
  #   steps:
  #     - checkout
  #     - run:
  #         name: Jest | Unit Test
  #         command: npm test

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/ecommerce_otop_frontend
    steps:
      - checkout
      - run:
          name: Firebase Deployjest
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_test:
          filters:
            branches:
              only: master
      # - test:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: master
